### ISSUE TITLE
Can't detect Plugin

### ISSUE THREAD

**Issue by dromeromarti** [PreciousBiscuit/cordova-plugin-zebra-scanner#1]
Hi!  I've been trying to run the plugin but I can't seem to get my cordova plugins to detect it.  Is there any additional steps required to installing/using the plugin?

**Comment by PreciousBiscuit** [comment]
Hello. I'm not aware of any additional steps I could have performed and I'm not aware of any dependencies that would be needed to run this plugin.
Installing it through cordova was enough for me to get it working.
`cordova plugin add https://github.com/PreciousBiscuit/cordova-plugin-zebra-scanner.git`
